name: dbus
version: 0.7.11

description:
  A native Dart implementation of the D-Bus message bus client. This package
  allows Dart applications to directly access services on the Linux desktop.

homepage: https://github.com/canonical/dbus.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

platforms:
  linux:
  windows:

dependencies:
  args: ^2.0.0
  ffi: ^2.0.0
  meta: ^1.3.0
  xml: ^6.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
  test_cov: ^1.0.1

executables:
  dart-dbus: dart_dbus
