name: dbus
version: 0.1.2

description:
  A native Dart implementation of the D-Bus message bus client. This package
  allows Dart applications to directly access services on the Linux desktop.

homepage: https://github.com/canonical/dbus.dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  args: ^2.0.0
  meta: ^1.2.4
  xml: ^5.0.0

dev_dependencies:
  pedantic: ^1.9.0

executables:
  dart-dbus:
