name: dbus
version: 0.0.0-dev.20

description:
  A native Dart implementation of the D-Bus message bus client. This package
  allows Dart applications to directly access services on the Linux desktop.

homepage: https://github.com/canonical/dbus.dart

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  args: ^1.6.0
  xml: ^4.3.0

dev_dependencies:
  pedantic: ^1.9.0

executables:
  dart-dbus:
